name: rentit
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  responsive_framework: ^1.1.0
  shared_preferences: ^2.0.15
  after_layout: ^1.2.0
  persistent_bottom_nav_bar: ^6.2.1
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/category/
    - assets/login.jpg
    - assets/icons/
    - assets/illustration.png
    - assets/illustration2.png
    - assets/illustration3.png
    - assets/splash.png

flutter_native_splash:
  color: "#42a5f5"
  image: "assets/splash.png"
  android_12:
    image: "assets/splash.png"
    color: "#42a5f5"
